In [1]:
#NUMPY STUDIES
import numpy as np

In [2]:
#Arrays and basic operations
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a + b)


[ 6  8 10 12]


In [3]:
#SEM NUMPY ELA CONCATENA
aa = [1,2,3,4]
bb = [5,6,7,8]
print(aa+bb)

[1, 2, 3, 4, 5, 6, 7, 8]


In [4]:
#Matrizes, reshape, e transpose
matriz = np.arange(9).reshape(3, 3)
print(matriz.T)  # Transposta


[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [5]:
print(matriz.mean(), matriz.std())


4.0 2.581988897471611


In [6]:
print(matriz[matriz > 4])  # Elementos maiores que 4


[5 6 7 8]


In [7]:
#join entre dataframes

clientes = pd.DataFrame({'id': [1, 2], 'nome': ['João', 'Maria']})
pedidos = pd.DataFrame({'cliente_id': [1, 1, 2], 'valor': [100, 200, 300]})

df_join = pd.merge(clientes, pedidos, left_on='id', right_on='cliente_id')


NameError: name 'pd' is not defined

In [ ]:
#  Nível 2: Pandas Intermediário
# Leia um CSV de vendas (vendas.csv com colunas: cliente, produto, valor, data).

# Calcule o total vendido por cliente.

# Adicione uma coluna "desconto" com 10% do valor.

# Filtre apenas vendas acima de R$200 com desconto.

In [ ]:
import pandas as pd
from IPython.display import display
df = pd.read_csv('vendas.csv')
display(df)

order_id  customer_id  order_status  order_date required_date  \
0         51         1108             4  2016-02-01    2016-02-03   
1         52          180             4  2016-02-02    2016-02-04   
2         53         1222             4  2016-02-03    2016-02-06   
3         54          224             4  2016-02-04    2016-02-06   
4         55         1011             4  2016-02-05    2016-02-08   
5         56          629             4  2016-02-06    2016-02-07   
6         57          786             4  2016-02-07    2016-02-10   
7         58          157             4  2016-02-08    2016-02-10   
8         59          367             4  2016-02-09    2016-02-12   
9         60          734             4  2016-02-10    2016-02-11   
10        61         1012             4  2016-02-11    2016-02-13   
11        62         1305             4  2016-02-12    2016-02-14   
12        63         1002             4  2016-02-13    2016-02-15   
13        64          803             4  2016-02-14    2016-02-15   
14        65          813             4  2016-02-15    2016-02-16   
15        66         1060             4  2016-02-16    2016-02-18   
16        67         1045             4  2016-02-17    2016-02-19   
17        68          880             4  2016-02-18    2016-02-19   
18        69          900             4  2016-02-19    2016-02-20   

   shipped_date  store_id  staff_id  
0    2016-02-03         1         3  
1    2016-02-06         3         2  
2    2016-02-06         2         8  
3    2016-02-07         3         7  
4    2016-02-08         2         4  
5    2016-02-08         2         2  
6    2016-02-11         2         6  
7    2016-02-12         1         3  
8    2016-02-12         3         3  
9    2016-02-12         2         3  
10   2016-02-15         2         4  
11   2016-02-14         2         3  
12   2016-02-17         3         6  
13   2016-02-16         2         3  
14   2016-02-17         1         6  
15   2016-02-19         3         4  
16   2016-02-20         3         6  
17   2016-02-19         2         6  
18   2016-02-22         3         8

In [12]:
# Calcule o total vendido por cliente.
sell_per_customer = df.groupby('customer_id')['customer_id'].count()
display(sell_per_customer)

customer_id
157     1
180     1
224     1
367     1
629     1
734     1
786     1
803     1
813     1
880     1
900     1
1002    1
1011    1
1012    1
1045    1
1060    1
1108    1
1222    1
1305    1
Name: customer_id, dtype: int64

In [ ]:
# Adicione uma coluna "desconto" com 10% do valor.
df['discount'] = 