In [1]:
#NUMPY STUDIES
import numpy as np

In [2]:
#Arrays and basic operations
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a + b)


[ 6  8 10 12]


In [3]:
#SEM NUMPY ELA CONCATENA
aa = [1,2,3,4]
bb = [5,6,7,8]
print(aa+bb)

[1, 2, 3, 4, 5, 6, 7, 8]


In [4]:
#Matrizes, reshape, e transpose
matriz = np.arange(9).reshape(3, 3)
print(matriz.T)  # Transposta


[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [5]:
print(matriz.mean(), matriz.std())


4.0 2.581988897471611


In [6]:
print(matriz[matriz > 4])  # Elementos maiores que 4


[5 6 7 8]


In [7]:
#join entre dataframes

clientes = pd.DataFrame({'id': [1, 2], 'nome': ['João', 'Maria']})
pedidos = pd.DataFrame({'cliente_id': [1, 1, 2], 'valor': [100, 200, 300]})

df_join = pd.merge(clientes, pedidos, left_on='id', right_on='cliente_id')


NameError: name 'pd' is not defined

In [ ]:
#  Nível 2: Pandas Intermediário
# Leia um CSV de vendas (vendas.csv com colunas: cliente, produto, valor, data).

# Calcule o total vendido por cliente.

# Adicione uma coluna "desconto" com 10% do valor.

# Filtre apenas vendas acima de R$200 com desconto.

In [13]:
import pandas as pd
from IPython.display import display
df = pd.read_csv('vendas.csv')
display(df)

cliente    produto   valor        data
0   Cliente_17  Produto D  153.45  2023-01-25
1   Cliente_10  Produto A  743.22  2023-02-28
2    Cliente_4  Produto C  298.99  2023-01-18
3    Cliente_6  Produto B  872.75  2023-01-30
4    Cliente_3  Produto A  120.50  2023-02-10
5    Cliente_8  Produto D  450.00  2023-01-21
6   Cliente_14  Produto C  670.13  2023-01-12
7   Cliente_12  Produto B  385.76  2023-02-14
8    Cliente_1  Produto A  998.40  2023-01-05
9   Cliente_19  Produto D  234.67  2023-01-17
10   Cliente_5  Produto C  523.89  2023-02-20
11   Cliente_2  Produto A  677.33  2023-01-28
12   Cliente_9  Produto B  390.00  2023-02-03
13  Cliente_15  Produto D  150.00  2023-01-22
14  Cliente_11  Produto C  785.10  2023-02-01
15   Cliente_7  Produto A  444.44  2023-02-25
16  Cliente_16  Produto B  832.25  2023-01-15
17  Cliente_18  Produto D  678.90  2023-02-07
18  Cliente_13  Produto A  102.20  2023-01-09
19  Cliente_20  Produto C  310.00  2023-02-12

In [17]:
# Calcule o total vendido por cliente.
sell_per_customer = df.groupby('cliente')['valor'].sum().sort_values(ascending=False)
display(sell_per_customer)

cliente
Cliente_1     998.40
Cliente_6     872.75
Cliente_16    832.25
Cliente_11    785.10
Cliente_10    743.22
Cliente_18    678.90
Cliente_2     677.33
Cliente_14    670.13
Cliente_5     523.89
Cliente_8     450.00
Cliente_7     444.44
Cliente_9     390.00
Cliente_12    385.76
Cliente_20    310.00
Cliente_4     298.99
Cliente_19    234.67
Cliente_17    153.45
Cliente_15    150.00
Cliente_3     120.50
Cliente_13    102.20
Name: valor, dtype: float64

In [25]:
# Adicione uma coluna "desconto" com 10% do valor.
df['discount'] = df['valor'] * 0.10
df['final_value'] =  (df['valor'] - df['discount']).round(2)
display(df)

cliente    produto   valor        data  discount  final_value
0   Cliente_17  Produto D  153.45  2023-01-25    15.345       138.10
1   Cliente_10  Produto A  743.22  2023-02-28    74.322       668.90
2    Cliente_4  Produto C  298.99  2023-01-18    29.899       269.09
3    Cliente_6  Produto B  872.75  2023-01-30    87.275       785.48
4    Cliente_3  Produto A  120.50  2023-02-10    12.050       108.45
5    Cliente_8  Produto D  450.00  2023-01-21    45.000       405.00
6   Cliente_14  Produto C  670.13  2023-01-12    67.013       603.12
7   Cliente_12  Produto B  385.76  2023-02-14    38.576       347.18
8    Cliente_1  Produto A  998.40  2023-01-05    99.840       898.56
9   Cliente_19  Produto D  234.67  2023-01-17    23.467       211.20
10   Cliente_5  Produto C  523.89  2023-02-20    52.389       471.50
11   Cliente_2  Produto A  677.33  2023-01-28    67.733       609.60
12   Cliente_9  Produto B  390.00  2023-02-03    39.000       351.00
13  Cliente_15  Produto D  150.00  2023-01-22    15.000       135.00
14  Cliente_11  Produto C  785.10  2023-02-01    78.510       706.59
15   Cliente_7  Produto A  444.44  2023-02-25    44.444       400.00
16  Cliente_16  Produto B  832.25  2023-01-15    83.225       749.02
17  Cliente_18  Produto D  678.90  2023-02-07    67.890       611.01
18  Cliente_13  Produto A  102.20  2023-01-09    10.220        91.98
19  Cliente_20  Produto C  310.00  2023-02-12    31.000       279.00

In [27]:
# Filtre apenas vendas acima de R$200 com desconto.
more_200 = df['valor'] > 200
filt_sales = df[more_200]
display(filt_sales)

cliente    produto   valor        data  discount  final_value
1   Cliente_10  Produto A  743.22  2023-02-28    74.322       668.90
2    Cliente_4  Produto C  298.99  2023-01-18    29.899       269.09
3    Cliente_6  Produto B  872.75  2023-01-30    87.275       785.48
5    Cliente_8  Produto D  450.00  2023-01-21    45.000       405.00
6   Cliente_14  Produto C  670.13  2023-01-12    67.013       603.12
7   Cliente_12  Produto B  385.76  2023-02-14    38.576       347.18
8    Cliente_1  Produto A  998.40  2023-01-05    99.840       898.56
9   Cliente_19  Produto D  234.67  2023-01-17    23.467       211.20
10   Cliente_5  Produto C  523.89  2023-02-20    52.389       471.50
11   Cliente_2  Produto A  677.33  2023-01-28    67.733       609.60
12   Cliente_9  Produto B  390.00  2023-02-03    39.000       351.00
14  Cliente_11  Produto C  785.10  2023-02-01    78.510       706.59
15   Cliente_7  Produto A  444.44  2023-02-25    44.444       400.00
16  Cliente_16  Produto B  832.25  2023-01-15    83.225       749.02
17  Cliente_18  Produto D  678.90  2023-02-07    67.890       611.01
19  Cliente_20  Produto C  310.00  2023-02-12    31.000       279.00

In [ ]:
# Nível 3: Desafio Completo
# Carregue dois CSVs (clientes.csv e compras.csv) e faça um merge.

# Crie uma coluna de "pontuação" baseada no total gasto por cliente.

# Agrupe por região e calcule o ticket médio.

# Exporte para um novo CSV chamado relatorio_final.csv.

In [49]:
#importando csvs
df_clientes = pd.read_csv('clientes.csv')
df_compras = pd.read_csv('compras.csv')
# display(df_clientes)
# display(df_compras)

#MERGE
df_merge = pd.merge(df_clientes, df_compras, left_on='cliente_id', right_on='cliente_id')
display(df_merge)


# Crie uma coluna de "pontuação" baseada no total gasto por cliente.
soma = df_merge.groupby('cliente_id')['valor'].sum().reset_index()
soma = soma.rename(columns={'valor': 'total_gasto'})
soma = soma.sort_values(by='total_gasto', ascending=False)

def pontuacao(value):
     if value < 300:
        return 'BRONZE'
     elif value < 500:
        return 'PRATA'
     else:
        return 'OURO'
soma['pontuacao'] = soma['total_gasto'].apply(pontuacao)
display(soma)


cliente_id               nome        região  compra_id   valor        data
0            1          Ana Silva       Sudeste        101  250.00  2023-01-15
1            1          Ana Silva       Sudeste        106  300.00  2023-02-01
2            1          Ana Silva       Sudeste        115   90.00  2023-02-25
3            2         Bruno Lima           Sul        102  180.50  2023-01-18
4            2         Bruno Lima           Sul        107  220.75  2023-02-05
5            3        Carla Souza      Nordeste        103  340.00  2023-01-20
6            3        Carla Souza      Nordeste        113  160.00  2023-02-21
7            4        Diego Rocha  Centro-Oeste        104  120.00  2023-01-21
8            5      Elaine Castro       Sudeste        105  410.25  2023-01-22
9            5      Elaine Castro       Sudeste        114  190.00  2023-02-23
10           6      Felipe Mendes         Norte        108  500.00  2023-02-10
11           7  Gabriela Teixeira           Sul        109  150.00  2023-02-12
12           8     Henrique Alves      Nordeste        110  200.00  2023-02-14
13           9    Isabela Martins       Sudeste        111  360.00  2023-02-18
14          10         João Pedro         Norte        112  280.00  2023-02-20

cliente_id  total_gasto pontuacao
0           1       640.00      OURO
4           5       600.25      OURO
2           3       500.00      OURO
5           6       500.00      OURO
1           2       401.25     PRATA
8           9       360.00     PRATA
9          10       280.00    BRONZE
7           8       200.00    BRONZE
6           7       150.00    BRONZE
3           4       120.00    BRONZE